### ISSUE TITLE
Handicap does not actually affect player health

### ISSUE THREAD

**Issue by GAnstandig** [pop4959/PopCraft#9]
Changes healthbar as expected, but does not affect actual health value.

**Comment by JonnyFrey** [comment]
can you describe the scenario that you are seeing? @Gabis1207

**Comment by JonnyFrey** [comment]
![handicapissue](https://user-images.githubusercontent.com/14628585/37256278-7c9c68aa-2515-11e8-9848-24520b5cb899.png)

**Comment by JonnyFrey** [comment]
![handicapissue](https://user-images.githubusercontent.com/14628585/37256289-a206f31c-2515-11e8-85c3-dc7e2b6ce1f7.png)
